INSERT INTO `db_proyecto_oci`.`procesos` (`NOMBRE_PROCESO`) 
VALUES 
	("Gestión de la Dirección Universitaria"),
    ("Gestión Administrativa y Financiera"),
	("Gestión de la Planeación y Desarrollo Institucional"),
	("Gestión de la Calidad"),
	("Gestión Académica"),
	("Gestión de la Investigación, Innovación e Interacción social"),
    ("Gestión de Cultura y Bienestar"),
	("Gestión de Control y del Mejoramiento Continuo");

INSERT INTO `db_proyecto_oci`.`tipo_control`
(`NOMBRE_TIPO_CONTROL`)
VALUES
	("Control Estratégico"),
	("Control de Gestión"),
	("Control Operativo"),
	("Control Legal"),
	("Control Concurrente");

INSERT INTO `db_proyecto_oci`.`roles`
(`NOMBRE_ROL`) VALUES
	('ROLE_administrador'),
	('ROLE_auditor'),
    ('ROLE_liderDeProceso'),
    ('ROLE_responsable');

INSERT INTO `db_proyecto_oci`.`dependencias`
(`DEPENDENCIA`) VALUES
	('Consejo Superior'),
	('Secretaría General'),
	('Área de Gestión Documental'),
	('Centro de Gestión de la Calidad y de la Acreditación Institucional'),
	('Centro de Gestión de las Comunicaciones'),
	('Oficina de Planeación y de Desarrollo Institucional'),
	('Oficina Jurídica'),
	('Oficina de Control Interno'),
	('Oficina de Relaciones Interinstitucionales e Internacionales'),
	('Consejo Académico'),
	('Centro de Regionalización'),
	('Centro de Posgrados'),
	('División de Admisiones, Registro y Control Académico (DARCA)'),
	('División de Gestión de Medios y Recursos Bibliográficos'),
	('Área de Egresados'),
	('Centro de Formación en Idiomas'),
	('Centro de Educación Continua, Abierta y Virtual – CECAV'),
	('División de Gestión del Talento Humano'),
	('Grupo de Gestión Pensional'),
	('Grupo de Control Interno Disciplinario'),
	('División de Tecnologías de la Información y las Comunicaciones'),
	('Área de Servicios de Información'),
	('Área de Recursos Tecnológicos'),
	('Área de Mantenimiento'),
	('Área de Mercadeo y Producción'),
	('Área de Contratación'),
	('División de Gestión de la Investigación'),
	('División de Gestión de la Cultura'),
	('División de Gestión de la Recreación y el Deporte'),
	('División de Gestión de Salud Integral y Desarrollo Humano'),
	('Facultad Ciencias de Contables, Económicas y Administrativas'),
	('Facultad de Derecho y Ciencias Políticas y Sociales'),
	('Facultad de Ciencias de la Salud'),
	('Facultad de Ingeniería Civil'),
	('Facultad de Ingeniería Electrónica y Telecomunicaciones'),
	('Facultad de Ciencias Naturales, Exactas y de la Educación'),
	('Facultad de Artes'),
	('Facultad de Ciencias Humanas y Sociales'),
	('Facultad de Ciencias Agrarias'),
	('Comité de Conciliación'),
	('Rectoría'),
	('Vicerrectoría');

INSERT INTO `db_proyecto_oci`.`cargos`
(`NOMBRE_CARGO`, `ID_DEPENDENCIA`) VALUES 
	("Rector", 41),
	("Vicerrector", 1),
    ("Vicerrector", 2),
    ("Vicerrector", 3),
    ("Vicerrector", 4),
    ("Vicerrector", 5),
    ("Vicerrector", 6),
    ("Vicerrector", 7),
    ("Vicerrector", 8),
    ("Vicerrector", 9),
    ("Vicerrector", 10),
    ("Vicerrector", 11),
    ("Vicerrector", 12),
    ("Vicerrector", 13),
    ("Vicerrector", 14),
    ("Vicerrector", 15),
    ("Vicerrector", 16),
    ("Vicerrector", 17),
    ("Vicerrector", 18),
    ("Vicerrector", 19),
    ("Vicerrector", 20),
    ("Vicerrector", 21),
    ("Vicerrector", 22),
    ("Vicerrector", 23),
    ("Vicerrector", 24),
    ("Vicerrector", 25),
    ("Vicerrector", 26),
    ("Vicerrector", 27),
    ("Vicerrector", 28),
    ("Vicerrector", 29),
    ("Vicerrector", 30),
    ("Vicerrector", 31),
    ("Vicerrector", 32),
    ("Vicerrector", 33),
    ("Vicerrector", 34),
    ("Vicerrector", 35),
    ("Vicerrector", 36),
    ("Vicerrector", 37),
    ("Vicerrector", 38),
    ("Vicerrector", 39),
    ("Vicerrector", 40),
    ("Vicerrector", 41),
    ("Vicerrector", 42),
	("Director de Centro", 1),
    ("Director de Centro", 2),
    ("Director de Centro", 3),
    ("Director de Centro", 4),
    ("Director de Centro", 5),
    ("Director de Centro", 6),
    ("Director de Centro", 7),
    ("Director de Centro", 8),
    ("Director de Centro", 9),
    ("Director de Centro", 10),
    ("Director de Centro", 11),
    ("Director de Centro", 12),
    ("Director de Centro", 13),
    ("Director de Centro", 14),
    ("Director de Centro", 15),
    ("Director de Centro", 16),
    ("Director de Centro", 17),
    ("Director de Centro", 18),
    ("Director de Centro", 19),
    ("Director de Centro", 20),
    ("Director de Centro", 21),
    ("Director de Centro", 22),
    ("Director de Centro", 23),
    ("Director de Centro", 24),
    ("Director de Centro", 25),
    ("Director de Centro", 26),
    ("Director de Centro", 27),
    ("Director de Centro", 28),
    ("Director de Centro", 29),
    ("Director de Centro", 30),
    ("Director de Centro", 31),
    ("Director de Centro", 32),
    ("Director de Centro", 33),
    ("Director de Centro", 34),
    ("Director de Centro", 35),
    ("Director de Centro", 36),
    ("Director de Centro", 37),
    ("Director de Centro", 38),
    ("Director de Centro", 39),
    ("Director de Centro", 40),
    ("Director de Centro", 41),
    ("Director de Centro", 42),
	("Secretario General", 1),
    ("Secretario General", 2),
    ("Secretario General", 3),
    ("Secretario General", 4),
    ("Secretario General", 5),
    ("Secretario General", 6),
    ("Secretario General", 7),
    ("Secretario General", 8),
    ("Secretario General", 9),
    ("Secretario General", 10),
    ("Secretario General", 11),
    ("Secretario General", 12),
    ("Secretario General", 13),
    ("Secretario General", 14),
    ("Secretario General", 15),
    ("Secretario General", 16),
    ("Secretario General", 17),
    ("Secretario General", 18),
    ("Secretario General", 19),
    ("Secretario General", 20),
    ("Secretario General", 21),
    ("Secretario General", 22),
    ("Secretario General", 23),
    ("Secretario General", 24),
    ("Secretario General", 25),
    ("Secretario General", 26),
    ("Secretario General", 27),
    ("Secretario General", 28),
    ("Secretario General", 29),
    ("Secretario General", 30),
    ("Secretario General", 31),
    ("Secretario General", 32),
    ("Secretario General", 33),
    ("Secretario General", 34),
    ("Secretario General", 35),
    ("Secretario General", 36),
    ("Secretario General", 37),
    ("Secretario General", 38),
    ("Secretario General", 39),
    ("Secretario General", 40),
    ("Secretario General", 41),
    ("Secretario General", 42),
	("Jefe de Oficina", 1),
    ("Jefe de Oficina", 2),
    ("Jefe de Oficina", 3),
    ("Jefe de Oficina", 4),
    ("Jefe de Oficina", 5),
    ("Jefe de Oficina", 6),
    ("Jefe de Oficina", 7),
    ("Jefe de Oficina", 8),
    ("Jefe de Oficina", 9),
    ("Jefe de Oficina", 10),
    ("Jefe de Oficina", 11),
    ("Jefe de Oficina", 12),
    ("Jefe de Oficina", 13),
    ("Jefe de Oficina", 14),
    ("Jefe de Oficina", 15),
    ("Jefe de Oficina", 16),
    ("Jefe de Oficina", 17),
    ("Jefe de Oficina", 18),
    ("Jefe de Oficina", 19),
    ("Jefe de Oficina", 20),
    ("Jefe de Oficina", 21),
    ("Jefe de Oficina", 22),
    ("Jefe de Oficina", 23),
    ("Jefe de Oficina", 24),
    ("Jefe de Oficina", 25),
    ("Jefe de Oficina", 26),
    ("Jefe de Oficina", 27),
    ("Jefe de Oficina", 28),
    ("Jefe de Oficina", 29),
    ("Jefe de Oficina", 30),
    ("Jefe de Oficina", 31),
    ("Jefe de Oficina", 32),
    ("Jefe de Oficina", 33),
    ("Jefe de Oficina", 34),
    ("Jefe de Oficina", 35),
    ("Jefe de Oficina", 36),
    ("Jefe de Oficina", 37),
    ("Jefe de Oficina", 38),
    ("Jefe de Oficina", 39),
    ("Jefe de Oficina", 40),
    ("Jefe de Oficina", 41),
    ("Jefe de Oficina", 42),
	("Jefe de Departamento", 1),
    ("Jefe de Departamento", 2),
    ("Jefe de Departamento", 3),
    ("Jefe de Departamento", 4),
    ("Jefe de Departamento", 5),
    ("Jefe de Departamento", 6),
    ("Jefe de Departamento", 7),
    ("Jefe de Departamento", 8),
    ("Jefe de Departamento", 9),
    ("Jefe de Departamento", 10),
    ("Jefe de Departamento", 11),
    ("Jefe de Departamento", 12),
    ("Jefe de Departamento", 13),
    ("Jefe de Departamento", 14),
    ("Jefe de Departamento", 15),
    ("Jefe de Departamento", 16),
    ("Jefe de Departamento", 17),
    ("Jefe de Departamento", 18),
    ("Jefe de Departamento", 19),
    ("Jefe de Departamento", 20),
    ("Jefe de Departamento", 21),
    ("Jefe de Departamento", 22),
    ("Jefe de Departamento", 23),
    ("Jefe de Departamento", 24),
    ("Jefe de Departamento", 25),
    ("Jefe de Departamento", 26),
    ("Jefe de Departamento", 27),
    ("Jefe de Departamento", 28),
    ("Jefe de Departamento", 29),
    ("Jefe de Departamento", 30),
    ("Jefe de Departamento", 31),
    ("Jefe de Departamento", 32),
    ("Jefe de Departamento", 33),
    ("Jefe de Departamento", 34),
    ("Jefe de Departamento", 35),
    ("Jefe de Departamento", 36),
    ("Jefe de Departamento", 37),
    ("Jefe de Departamento", 38),
    ("Jefe de Departamento", 39),
    ("Jefe de Departamento", 40),
	("Coordinador de Programa", 32),
    ("Coordinador de Programa", 33),
    ("Coordinador de Programa", 34),
    ("Coordinador de Programa", 35),
    ("Coordinador de Programa", 36),
    ("Coordinador de Programa", 37),
    ("Coordinador de Programa", 38),
    ("Coordinador de Programa", 39),
    ("Coordinador de Programa", 40),
	("Profesor", 32),
    ("Profesor", 33),
    ("Profesor", 34),
    ("Profesor", 35),
    ("Profesor", 36),
    ("Profesor", 37),
    ("Profesor", 38),
    ("Profesor", 39),
    ("Profesor", 40),
	("Asesor", 1),
    ("Asesor", 2),
    ("Asesor", 3),
    ("Asesor", 4),
    ("Asesor", 5),
    ("Asesor", 6),
    ("Asesor", 7),
    ("Asesor", 8),
    ("Asesor", 9),
    ("Asesor", 10),
    ("Asesor", 11),
    ("Asesor", 12),
    ("Asesor", 13),
    ("Asesor", 14),
    ("Asesor", 15),
    ("Asesor", 16),
    ("Asesor", 17),
    ("Asesor", 18),
    ("Asesor", 19),
    ("Asesor", 20),
    ("Asesor", 21),
    ("Asesor", 22),
    ("Asesor", 23),
    ("Asesor", 24),
    ("Asesor", 25),
    ("Asesor", 26),
    ("Asesor", 27),
    ("Asesor", 28),
    ("Asesor", 29),
    ("Asesor", 30),
    ("Asesor", 31),
    ("Asesor", 32),
    ("Asesor", 33),
    ("Asesor", 34),
    ("Asesor", 35),
    ("Asesor", 36),
    ("Asesor", 37),
    ("Asesor", 38),
    ("Asesor", 39),
    ("Asesor", 40),
    ("Asesor", 41),
    ("Asesor", 42),
	("Profesional Especializado", 1),
    ("Profesional Especializado", 2),
    ("Profesional Especializado", 3),
    ("Profesional Especializado", 4),
    ("Profesional Especializado", 5),
    ("Profesional Especializado", 6),
    ("Profesional Especializado", 7),
    ("Profesional Especializado", 8),
    ("Profesional Especializado", 9),
    ("Profesional Especializado", 10),
    ("Profesional Especializado", 11),
    ("Profesional Especializado", 12),
    ("Profesional Especializado", 13),
    ("Profesional Especializado", 14),
    ("Profesional Especializado", 15),
    ("Profesional Especializado", 16),
	("Profesional Especializado", 17),
    ("Profesional Especializado", 18),
    ("Profesional Especializado", 19),
    ("Profesional Especializado", 20),
    ("Profesional Especializado", 21),
    ("Profesional Especializado", 22),
    ("Profesional Especializado", 23),
    ("Profesional Especializado", 24),
    ("Profesional Especializado", 25),
    ("Profesional Especializado", 26),
    ("Profesional Especializado", 27),
    ("Profesional Especializado", 28),
    ("Profesional Especializado", 29),
    ("Profesional Especializado", 30),
    ("Profesional Especializado", 31),
    ("Profesional Especializado", 32),
    ("Profesional Especializado", 33),
    ("Profesional Especializado", 34),
    ("Profesional Especializado", 35),
    ("Profesional Especializado", 36),
	("Profesional Especializado", 37),
    ("Profesional Especializado", 38),
    ("Profesional Especializado", 39),
    ("Profesional Especializado", 40),
    ("Profesional Especializado", 41),
    ("Profesional Especializado", 42),
	("Profesional Universitario", 1),
	("Profesional Universitario", 2),
    ("Profesional Universitario", 3),
    ("Profesional Universitario", 4),
    ("Profesional Universitario", 5),
    ("Profesional Universitario", 6),
    ("Profesional Universitario", 7),
    ("Profesional Universitario", 8),
    ("Profesional Universitario", 9),
    ("Profesional Universitario", 10),
    ("Profesional Universitario", 11),
    ("Profesional Universitario", 12),
    ("Profesional Universitario", 13),
    ("Profesional Universitario", 14),
    ("Profesional Universitario", 15),
    ("Profesional Universitario", 16),
    ("Profesional Universitario", 17),
    ("Profesional Universitario", 18),
    ("Profesional Universitario", 19),
    ("Profesional Universitario", 20),
    ("Profesional Universitario", 21),
    ("Profesional Universitario", 22),
    ("Profesional Universitario", 23),
    ("Profesional Universitario", 24),
    ("Profesional Universitario", 25),
    ("Profesional Universitario", 26),
    ("Profesional Universitario", 27),
    ("Profesional Universitario", 28),
    ("Profesional Universitario", 29),
    ("Profesional Universitario", 30),
    ("Profesional Universitario", 31),
    ("Profesional Universitario", 32),
    ("Profesional Universitario", 33),
    ("Profesional Universitario", 34),
    ("Profesional Universitario", 35),
    ("Profesional Universitario", 36),
    ("Profesional Universitario", 37),
    ("Profesional Universitario", 38),
    ("Profesional Universitario", 39),
    ("Profesional Universitario", 40),
    ("Profesional Universitario", 41),
    ("Profesional Universitario", 42),
    ("Técnico Administrativo", 1),
    ("Técnico Administrativo", 2),
    ("Técnico Administrativo", 3),
    ("Técnico Administrativo", 4),
    ("Técnico Administrativo", 5),
    ("Técnico Administrativo", 6),
    ("Técnico Administrativo", 7),
    ("Técnico Administrativo", 8),
    ("Técnico Administrativo", 9),
    ("Técnico Administrativo", 10),
    ("Técnico Administrativo", 11),
    ("Técnico Administrativo", 12),
    ("Técnico Administrativo", 13),
    ("Técnico Administrativo", 14),
    ("Técnico Administrativo", 15),
    ("Técnico Administrativo", 16),
    ("Técnico Administrativo", 17),
    ("Técnico Administrativo", 18),
    ("Técnico Administrativo", 19),
    ("Técnico Administrativo", 20),
    ("Técnico Administrativo", 21),
    ("Técnico Administrativo", 22),
    ("Técnico Administrativo", 23),
    ("Técnico Administrativo", 24),
    ("Técnico Administrativo", 25),
    ("Técnico Administrativo", 26),
    ("Técnico Administrativo", 27),
    ("Técnico Administrativo", 28),
    ("Técnico Administrativo", 29),
    ("Técnico Administrativo", 30),
    ("Técnico Administrativo", 31),
    ("Técnico Administrativo", 32),
    ("Técnico Administrativo", 33),
    ("Técnico Administrativo", 34),
    ("Técnico Administrativo", 35),
    ("Técnico Administrativo", 36),
    ("Técnico Administrativo", 37),
    ("Técnico Administrativo", 38),
    ("Técnico Administrativo", 39),
    ("Técnico Administrativo", 40),
    ("Técnico Administrativo", 41),
    ("Técnico Administrativo", 42),
	("Técnico Operativo", 1),
    ("Técnico Operativo", 2),
    ("Técnico Operativo", 3),
    ("Técnico Operativo", 4),
    ("Técnico Operativo", 5),
    ("Técnico Operativo", 6),
    ("Técnico Operativo", 7),
    ("Técnico Operativo", 8),
    ("Técnico Operativo", 9),
    ("Técnico Operativo", 10),
    ("Técnico Operativo", 11),
    ("Técnico Operativo", 12),
    ("Técnico Operativo", 13),
    ("Técnico Operativo", 14),
    ("Técnico Operativo", 15),
    ("Técnico Operativo", 16),
    ("Técnico Operativo", 17),
    ("Técnico Operativo", 18),
    ("Técnico Operativo", 19),
    ("Técnico Operativo", 20),
    ("Técnico Operativo", 21),
    ("Técnico Operativo", 22),
    ("Técnico Operativo", 23),
    ("Técnico Operativo", 24),
    ("Técnico Operativo", 25),
    ("Técnico Operativo", 26),
    ("Técnico Operativo", 27),
    ("Técnico Operativo", 28),
    ("Técnico Operativo", 29),
    ("Técnico Operativo", 30),
    ("Técnico Operativo", 31),
    ("Técnico Operativo", 32),
    ("Técnico Operativo", 33),
    ("Técnico Operativo", 34),
    ("Técnico Operativo", 35),
    ("Técnico Operativo", 36),
    ("Técnico Operativo", 37),
    ("Técnico Operativo", 38),
    ("Técnico Operativo", 39),
    ("Técnico Operativo", 40),
    ("Técnico Operativo", 41),
    ("Técnico Operativo", 42),
    ("Secretario Ejecutivo", 1),
    ("Secretario Ejecutivo", 2),
    ("Secretario Ejecutivo", 3),
    ("Secretario Ejecutivo", 4),
    ("Secretario Ejecutivo", 5),
    ("Secretario Ejecutivo", 6),
    ("Secretario Ejecutivo", 7),
    ("Secretario Ejecutivo", 8),
    ("Secretario Ejecutivo", 9),
    ("Secretario Ejecutivo", 10),
    ("Secretario Ejecutivo", 11),
    ("Secretario Ejecutivo", 12),
    ("Secretario Ejecutivo", 13),
    ("Secretario Ejecutivo", 14),
    ("Secretario Ejecutivo", 15),
    ("Secretario Ejecutivo", 16),
    ("Secretario Ejecutivo", 17),
    ("Secretario Ejecutivo", 18),
    ("Secretario Ejecutivo", 19),
    ("Secretario Ejecutivo", 20),
	("Secretario Ejecutivo", 21),
    ("Secretario Ejecutivo", 22),
    ("Secretario Ejecutivo", 23),
    ("Secretario Ejecutivo", 24),
    ("Secretario Ejecutivo", 25),
    ("Secretario Ejecutivo", 26),
    ("Secretario Ejecutivo", 27),
    ("Secretario Ejecutivo", 28),
    ("Secretario Ejecutivo", 29),
    ("Secretario Ejecutivo", 30),
    ("Secretario Ejecutivo", 31),
    ("Secretario Ejecutivo", 32),
    ("Secretario Ejecutivo", 33),
    ("Secretario Ejecutivo", 34),
    ("Secretario Ejecutivo", 35),
    ("Secretario Ejecutivo", 36),
    ("Secretario Ejecutivo", 37),
    ("Secretario Ejecutivo", 38),
    ("Secretario Ejecutivo", 39),
    ("Secretario Ejecutivo", 40),
    ("Secretario Ejecutivo", 41),
    ("Secretario Ejecutivo", 42),
    ("Auxiliar Administrativo", 1),
    ("Auxiliar Administrativo", 2),
    ("Auxiliar Administrativo", 3),
    ("Auxiliar Administrativo", 4),
    ("Auxiliar Administrativo", 5),
    ("Auxiliar Administrativo", 6),
    ("Auxiliar Administrativo", 7),
    ("Auxiliar Administrativo", 8),
    ("Auxiliar Administrativo", 9),
    ("Auxiliar Administrativo", 10),
    ("Auxiliar Administrativo", 11),
    ("Auxiliar Administrativo", 12),
    ("Auxiliar Administrativo", 13),
    ("Auxiliar Administrativo", 14),
    ("Auxiliar Administrativo", 15),
    ("Auxiliar Administrativo", 16),
    ("Auxiliar Administrativo", 17),
    ("Auxiliar Administrativo", 18),
    ("Auxiliar Administrativo", 19),
    ("Auxiliar Administrativo", 20),
    ("Auxiliar Administrativo", 21),
    ("Auxiliar Administrativo", 22),
    ("Auxiliar Administrativo", 23),
    ("Auxiliar Administrativo", 24),
    ("Auxiliar Administrativo", 25),
    ("Auxiliar Administrativo", 26),
    ("Auxiliar Administrativo", 27),
    ("Auxiliar Administrativo", 28),
    ("Auxiliar Administrativo", 29),
    ("Auxiliar Administrativo", 30),
    ("Auxiliar Administrativo", 31),
    ("Auxiliar Administrativo", 32),
    ("Auxiliar Administrativo", 33),
    ("Auxiliar Administrativo", 34),
    ("Auxiliar Administrativo", 35),
    ("Auxiliar Administrativo", 36),
    ("Auxiliar Administrativo", 37),
    ("Auxiliar Administrativo", 38),
    ("Auxiliar Administrativo", 39),
    ("Auxiliar Administrativo", 40),
    ("Auxiliar Administrativo", 41),
    ("Auxiliar Administrativo", 42),
    ("Supervisor", 1),
    ("Supervisor", 2),
    ("Supervisor", 3),
    ("Supervisor", 4),
    ("Supervisor", 5),
    ("Supervisor", 6),
    ("Supervisor", 7),
    ("Supervisor", 8),
    ("Supervisor", 9),
    ("Supervisor", 10),
	("Supervisor", 11),
    ("Supervisor", 22),
    ("Supervisor", 23),
    ("Supervisor", 24),
    ("Supervisor", 25),
    ("Supervisor", 26),
    ("Supervisor", 27),
    ("Supervisor", 28),
    ("Supervisor", 29),
    ("Supervisor", 30),
    ("Supervisor", 31),
    ("Supervisor", 32),
    ("Supervisor", 33),
    ("Supervisor", 34),
    ("Supervisor", 35),
    ("Supervisor", 36),
    ("Supervisor", 37),
    ("Supervisor", 38),
    ("Supervisor", 39),
    ("Supervisor", 40),
    ("Supervisor", 41),
    ("Supervisor", 42),
    ("Operario Calificado", 1),
    ("Operario Calificado", 2),
    ("Operario Calificado", 3),
    ("Operario Calificado", 4),
    ("Operario Calificado", 5),
    ("Operario Calificado", 6),
    ("Operario Calificado", 7),
    ("Operario Calificado", 8),
    ("Operario Calificado", 9),
    ("Operario Calificado", 10),
	("Operario Calificado", 11),
    ("Operario Calificado", 12),
    ("Operario Calificado", 13),
    ("Operario Calificado", 14),
    ("Operario Calificado", 15),
    ("Operario Calificado", 16),
    ("Operario Calificado", 17),
    ("Operario Calificado", 18),
    ("Operario Calificado", 19),
    ("Operario Calificado", 20),
    ("Operario Calificado", 21),
    ("Operario Calificado", 22),
    ("Operario Calificado", 23),
    ("Operario Calificado", 24),
    ("Operario Calificado", 25),
    ("Operario Calificado", 26),
    ("Operario Calificado", 27),
    ("Operario Calificado", 28),
    ("Operario Calificado", 29),
    ("Operario Calificado", 30),
	("Operario Calificado", 31),
    ("Operario Calificado", 32),
    ("Operario Calificado", 33),
    ("Operario Calificado", 34),
    ("Operario Calificado", 35),
    ("Operario Calificado", 36),
    ("Operario Calificado", 37),
    ("Operario Calificado", 38),
    ("Operario Calificado", 39),
    ("Operario Calificado", 40),
    ("Operario Calificado", 41),
    ("Operario Calificado", 42);

INSERT INTO `db_proyecto_oci`.`personas` 
(`ID_CARGO`, `NOMBRES`, `APELLIDOS`, `IDENTIFICACION`, `TIPO_DOCUMENTO`, `EMAIL`) VALUES
(1, "Usuario", "Administrador", 12345, "CC", "admin@prod.com"), 
(308, "Control", "Interno", 891500319, "CC", "cinterno@unicauca.edu.co");

INSERT INTO `db_proyecto_oci`.`usuarios` 
(`ID_ROL`, `ID_PERSONA`, `USUARIO`, `PASSWORD`) VALUES
(1, 1, "admin@prod.com", "$2a$10$/4l7prK8aRkerY184GUtIejKj6ZVnUpwpoJ2U7qEbnHW7d1Sdc5k2"),
(1, 2, "cinterno@unicauca.edu.co", "$10$SB7Xd4OTz5LbjNrdIv74WeqIORTzZwTn3tL07JTEPSpJqZytHNGjG");
