# fly.toml app configuration file generated for oci-backend-winter-pine-4070 on 2023-11-19T16:18:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oci-backend-winter-pine-4070"
primary_region = "bog"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
